### ISSUE TITLE
Proper static frontend and separate repo?

### ISSUE THREAD

**Issue by rtsao** [L33T-KR3W/soundcasts-server#11]
Is there a way we can host the static front-end with GitHub Pages? Ideally the static front-end and server live in separate repos.

It seems silly to host static content with node.js

**Comment by scott113341** [comment]
We can host it with nginx, otherwise the node and static sites will have to be on separate subdomains

**Comment by scott113341** [comment]
https://github.com/L33T-KR3W/soundcasts-web
