### ISSUE TITLE
Bug Discovered in Production

### ISSUE THREAD

**Issue by scott113341** [L33T-KR3W/soundcasts-server#18]
Going to http://api.soundcasts.net/soundcast.xml?title=Hannah%20Wants%3A%20Mixtapes&userId=hannah_wants&regexString=mixtape resulted in the following error (deployment has since been rolled back to commit 779d1fb):

```json
{
    "error": "Invalid URI \"undefined/users/hannah_wants\""
}
```

I believe this is related to #13, where config.js was added.  You break it, you fix it @rtsao

**Comment by rtsao** [comment]
https://github.com/L33T-KR3W/soundcasts-server/pull/19
