### ISSUE TITLE
Linting, tests, coverage, CI, etc.

### ISSUE THREAD

**Issue by rtsao** [L33T-KR3W/soundcasts-server#2]
Need to add linting, tests, Travis CI, coverage, Coveralls.

- [ ] Linting https://github.com/L33T-KR3W/soundcasts-server/issues/20
- [x] Tests
- [x] Travis CI
- [x] Code coverage
- [x] Coveralls

**Comment by scott113341** [comment]
Marking Travis CI as finished #16

**Comment by rtsao** [comment]
Seperate issue for Linting: https://github.com/L33T-KR3W/soundcasts-server/issues/20
