### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by rtsao** [L33T-KR3W/soundcasts-server#20]
Let's bikeshed the crap out of this one

**Comment by scott113341** [comment]
I like this one
![image](https://cloud.githubusercontent.com/assets/1910118/10534911/b688388c-7392-11e5-80e7-d5f7e433fecb.png)

**Comment by scott113341** [comment]
Live edge bike shed?
![image](https://cloud.githubusercontent.com/assets/1910118/10536024/b94b414a-739c-11e5-8582-c16f0f80e1a1.png)

**Comment by rtsao** [comment]
![image](http://www.ridgerunnermill.com/_/rsrc/1358117086485/customer-s-paneling-and-siding-projects/Mike%20Andersons%20shed%202.JPG?height=266&width=400)

**Comment by scott113341** [comment]
Closing for now.  We need the `no-if` lint set up first.  And probably some new tooling.
