### ISSUE TITLE
Use Redis for caching

### ISSUE THREAD

**Issue by rtsao** [L33T-KR3W/soundcasts-server#3]
Can we fit in the 30MB free redis cloud instance?

**Comment by scott113341** [comment]
Maybe.  We get 496MB from MongoLab free tier.  

Currently we have 4 documents in Mongo, which takes up 150KB.  That's only 200 documents for 30MB.  TTL will help out, but the podcast episodes are kinda big because they have large text descriptions.

**Comment by scott113341** [comment]
See #1, closing as wontfix
