### ISSUE TITLE
Use something other than Heroku

### ISSUE THREAD

**Issue by scott113341** [L33T-KR3W/soundcasts-server#5]
Got an email from Heroku this morning:

![image](https://cloud.githubusercontent.com/assets/1910118/8793018/f84dcabe-2f24-11e5-98fb-a14062d4954d.png)

Looking at the logs, something is hitting the server at pretty short intervals to check for updates, so Heroku is going to become unacceptable very soon.

**Comment by rtsao** [comment]
I actually subscribed to a podcast to iTunes, could it be that be causing the frequent checks?

**Comment by scott113341** [comment]
Yeah, either that or podcasts that I subscribed to on [Pocket Casts](http://www.shiftyjelly.com/pocketcasts).  Either way, it's not ok for us to have 6 hours of downtime per day haha

**Comment by mmedal** [comment]
I have a couple droplets on DO we can use. Any of the infra backs we discussed on facebook are chill. If we wanted to go ham, Kubernetes v1 launched today. #production

**Comment by scott113341** [comment]
Finished: using Digital Ocean for the API (soundcasts-server) and GitHub Pages for the UI (soundcasts-web)
